Middleware: sandbox::Cube Class Reference
sandbox::Cube Class Reference
#include <Cube.hpp>
Public Member Functions
Cube (int32_t width, int32_t height, int32_t depth)
~Cube ()
Generic destructor.
int32_t width ()
int32_t height ()
int32_t depth ()
int64_t area ()
Detailed Description
This is Cube, it operates on int32_t and can compute areas
Definition at line 10 of file Cube.hpp.
Constructor & Destructor Documentation
Cube()
sandbox::Cube::Cube (int32_t width, int32_t height, int32_t depth) inline
Constructor which creates a cube by taking three values in
Parameters
width The width value
height The height value
depth The depth value
Definition at line 17 of file Cube.hpp.
References width().
~Cube()
sandbox::Cube::~Cube () inline
Generic destructor.
Definition at line 25 of file Cube.hpp.
Member Function Documentation
area()
int64_t sandbox::Cube::area () inline
Returns the area (width x height)
Returns
Value of area
Definition at line 52 of file Cube.hpp.
Referenced by main().
depth()
int32_t sandbox::Cube::depth () inline
Returns the depth value
Returns
depth
Definition at line 45 of file Cube.hpp.
height()
int32_t sandbox::Cube::height () inline
Returns the height value
Returns
height
Definition at line 38 of file Cube.hpp.
width()
int32_t sandbox::Cube::width () inline
Returns the width value
Returns
width
Definition at line 31 of file Cube.hpp.
Referenced by Cube().
The documentation for this class was generated from the following file:
cpp/Cube.hpp